---
name: Checks

# Trigger to the jobs
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # Machine available on github actions. It already has docker and docker-compose installed.
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # Uses previous configured action
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # This is a checkout to make the code available to the jobs
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"